### ISSUE TITLE
Add Support for get-site-ip.com

### ISSUE THREAD

**Issue by ZeroDot1** [ninoseki/mitaka#11]
http://get-site-ip.com/ 
This page is the easiest way to find the IP address of a domain.

@ninoseki The browser extension is a very good tool, I use it very often, thanks for developing this tool.

**Comment by ninoseki** [comment]
@ZeroDot1 Thank you for feedback always.
Just a question,  VT’s domain search feature has a `Passive Dns Replication` section and I think it meets your needs. Isn’t it?

**Comment by ZeroDot1** [comment]
Yes, you are right, the search function in Virus Total is enough. 
Sorry, it was a stupid, thoughtless request from me.

**Comment by ninoseki** [comment]
@ZeroDot1 It's no problem for me. Please feel free to give me a feature request. :D
