### ISSUE TITLE
Disregard Issue/Request.  Cannot find a way to delete this request.

### ISSUE THREAD

**Issue by ejruprecht** [ninoseki/mitaka#12]
Disregard Issue/Request.  Cannot find a way to delete this request.

**Comment by ninoseki** [comment]
@ejruprecht Sorry, I cannot imagine what you mean. (What is "that URL"?)
Could you explain it a little bit more detail, please?

**Comment by ejruprecht** [comment]
HI, Sorry, I agree it's not too clear.  As an example, if google.com was in
plaintext, we currently have the ability to search for it on urlscan.io or
scan it on urlscan.io but it would be nice if we had an option to also just
open the website in a new tab by right clicking and having an option to "Go
to URL"

**Comment by ninoseki** [comment]
<img width="654" alt="screen_shot_2018-06-17_at_2_15_48_pm" src="https://user-images.githubusercontent.com/291028/41504969-08f8b68a-7239-11e8-9a12-af7e3471dd09.png">

When selecting a URL/domain, Chrome context menus show "Go to" menu. It navigates you to a website of the URL/domain.
Isn't it enough for you?
