### ISSUE TITLE
Add SecurityTrails 

### ISSUE THREAD

**Issue by ZeroDot1** [ninoseki/mitaka#13]
I use SecurityTrails from time to time, and it would be very useful if you could do a search on SecurityTrails directly from the add-on. 

https://securitytrails.com/ 
API Docs: https://docs.securitytrails.com/

**Comment by ninoseki** [comment]
@ZeroDot1 thank you for your suggestion.
I'm not a user of SecurityTrails but it seems a nice one. I'll make it.

**Comment by ZeroDot1** [comment]
Thank you very much.
Keep up the good work.

**Comment by ninoseki** [comment]
@ZeroDot1 
I made some changes (#14) and pushed the extension to Chrome Web Store.
The new version of the extension will be available within hours.

**Comment by ZeroDot1** [comment]
Thank you very much for your good work.
