### ISSUE TITLE
Add Pulsedive integration

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/mitaka#15]
- Pulsedive: https://pulsedive.com/

It looks like a good one but I cannot find a good way to handle a search on the WebUI.
Is opening a JSON file (like a below link) in the browser useful for users? I'm not sure.
- https://pulsedive.com/api/info.php?indicator=github.com&pretty=1

**Comment by ZeroDot1** [comment]
This would be very helpful for me, because you can see all important information at a single click.

**Comment by ninoseki** [comment]
I realized that I could use their search Web UI as follows:
- https://pulsedive.com/indicator/?ioc=Z2l0aHViLmNvbQ==
  - `Z2l0aHViLmNvbQ==` => `github.com`(Base64 decoded value)
- https://pulsedive.com/indicator/?ioc=MS4xLjEuMQ==
  - `MS4xLjEuMQ==` => `1.1.1.1` (Base64 decoded value)

I thinks it's better than a JSON file, what do you think? @ZeroDot1

**Comment by ZeroDot1** [comment]
@ninoseki Yeah, it's better than a json file.
Keep up the good work.

**Comment by ninoseki** [comment]
It was implemented in the new version (#16).
