### ISSUE TITLE
Add netcraft

### ISSUE THREAD

**Issue by Avileox** [ninoseki/mitaka#194]
https://www.netcraft.com/

**Search for subdomains**
https://searchdns.netcraft.com/?restriction=site+contains&host=*.google.com.*&lookup=wait..&position=limited

**Comment by ninoseki** [comment]
Could you give more detailed information?
(Please refer to #164 or #191 . This kind of information is useful for implementation.)

**Comment by Avileox** [comment]
- ### Netcraft (https://www.netcraft.com/)
- 1 **Find out what technologies are powering any [website:**] **(Supports IP and domain)**
- * IP(`74.125.193.101` ): https://toolbar.netcraft.com/site_report?url=74.125.193.101
- * Domain(`google.com`): https://toolbar.netcraft.com/site_report?url=http://www.google.com
- 2 **Search Web by Domain** **(Supports IP and domain)**
- **Site contains**
- * * Domain(`google.com`): https://searchdns.netcraft.com/?restriction=site+contains&host=google.com&lookup=wait..&position=limited
- **Site starts**
 - * * Domain(`google.com`): https://searchdns.netcraft.com/?restriction=site+starts+with&host=google.com&lookup=wait..&position=limited
- **Site ends**
- * * Domain(`google.com`): https://searchdns.netcraft.com/?restriction=site+ends+with&host=google.com&lookup=wait..&position=limited
- **Subdomain matches**
- * * Domain(`google.com`): https://searchdns.netcraft.com/?restriction=subdomain+matches&host=google.com&lookup=wait..&position=limited
