### ISSUE TITLE
Add hackertarget.com/ip-tools/

### ISSUE THREAD

**Issue by Avileox** [ninoseki/mitaka#195]
https://hackertarget.com/ip-tools/

### IP and Network Tools

Traceroute | Using mtr an advanced traceroute tool trace the path of an Internet connection.
-- | --
Test Ping | A common tool for testing connectivity to a host, perform a ping from our server.
DNS Lookup | Find DNS records for a domain, results are determined using the dig DNS tool.
Find (A) Records | Find forward DNS (A) records for a domain.
Reverse DNS | Find Reverse DNS records for an IP address or a range of IP addresses.
Find Shared DNS Servers | Find hosts sharing DNS servers.
Zone Transfer | Online Test of a zone transfer that will attempt to get all DNS records for a target domain
Whois Lookup | Determine the registered owner of a domain or IP address block with the whois tool.
GeoIP Lookup | Find the location of an IP address using the GeoIP lookup location tool.
Reverse IP | Discover web hosts sharing an IP address with a reverse IP lookup.
TCP Port Scan | Determine the status of an Internet facing service or firewall
UDP Port Scan | Online UDP port scan available for common UDP services
Subnet Lookup Online | Determine the properties of a network subnet
HTTP Headers | View HTTP Headers of a web site. The HTTP Headers reveal system and web application details.
Page Links | Dump all the links from a web page.
AS Lookup | Get Autonomous System Number or ASN details from an AS or an IP address.

**Comment by ninoseki** [comment]
Could you give more detailed information?
(Please refer to #164 or #191 . This kind of information is useful for implementation.)

**Comment by ninoseki** [comment]
I close this issue because of a lack of response for a long time.
