### ISSUE TITLE
Add ThreatConnect lookup

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/mitaka#248]
- ThreatConnect(https://app.threatconnect.com):
  - Supported types: ip, domain
  - IP(`1.1.1.1`): https://app.threatconnect.com/auth/indicators/details/address.xhtml?address=1.1.1.1#/
  - Domain(`github.com`): https://app.threatconnect.com/auth/indicators/details/host.xhtml?host=github.com#/

**Comment by ninoseki** [comment]
Implemented in #257.

**Comment by zero77** [comment]
I will have a more in-depth look but, it looks like the api has been updated and it now may or may not be possible.
