### ISSUE TITLE
Suggested improvements to the AMO page for Mitaka

### ISSUE THREAD

**Issue by grahamperrin** [ninoseki/mitaka#302]
1. Include some screenshots – maybe reuse the shots that were taken for Chrome Web Store
2. add [an easy-to-read description](https://extensionworkshop.com/documentation/publish/add-on-policies/#content); include a link to a page about OSINT (don't assume that everyone who browses AMO will know the acronym)
3. for the support link, refer to GitHub. 

(I discovered this area in a roundabout way, via an `about:addons` **non**-clickable representation of the link that's at <https://addons.mozilla.org/addon/mitaka/versions/0.61.0/updateinfo/>.)

[Create an appealing listing | Extension Workshop](https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/)

Thanks :+1:

**Comment by ninoseki** [comment]
@grahamperrin could you write a draft for it, please?

**Comment by ninoseki** [comment]
Close this issue because there is no action for months.
