### ISSUE TITLE
Selecting domain in hyperlink does not give domain searches

### ISSUE THREAD

**Issue by wesinator** [ninoseki/mitaka#319]
To reproduce:
 - highlight text in `<a href="http://example.com">example.com</a>`

<img width="310" alt="image" src="https://user-images.githubusercontent.com/5124946/68500488-d5acae80-0229-11ea-9fe2-855d62d88e0e.png">
(Firefox)

**Expected:** matches domain text and offers domain searches

**Comment by ninoseki** [comment]
It is a specification and it's an expected behavior for me.

**Comment by wesinator** [comment]
> 
> 
> It is a specification and it's an expected behavior for me.

Can you change it to also suggest domain if the text matches a domain ?
