### ISSUE TITLE
Add bitcoinwhoswho

### ISSUE THREAD

**Issue by sekisanchi** [ninoseki/mitaka#327]
Hi, 
Thanks for providing the super utility!!
Can we have 
https://bitcoinwhoswho.com/
(ex.  https://bitcoinwhoswho.com/address/1Dce8kjMfFzFh48a9njNvqZiqGe7mR39ix )    
next to bitcoinabusedatabase with the same flow?

**Comment by ninoseki** [comment]
Thanks for a nice suggestion.
It is implemented and it will be included in the next release.
