### ISSUE TITLE
Firefox 72.0.2 IP / IoC selector randomly does not work

### ISSUE THREAD

**Issue by TrinityIsStillMyName** [ninoseki/mitaka#379]
First of all thank you for this very nice addon. I tested it on firefox and sometimes the selector does not parse the highlighted text/ip/url. After right clicking and selecting mitaka it still shows the options for the previous selected text/ip/url. 
Environment: Firefox 72.0.2
Active addons: ublock, umatrix

I can provide logs if you tell me how to generate them

**Comment by ninoseki** [comment]
@TrinityIsStillMyName Updating the add-on or reinstalling the add-on might work.
