### ISSUE TITLE
Firefox 72.0.2 | Environment proxy variables are not used for "Scan this IP/URL/..."

### ISSUE THREAD

**Issue by TrinityIsStillMyName** [ninoseki/mitaka#380]
When using mitaka on firefox 72.0.2 with proxy setting "Use system proxy settings", it looks like the addon does not use proxy variables from system. I configured API keys for several services and when highlighting an IP and selecting "Scan this IP/URL/...", there appears a generic pop-up error message from my DE KDE:
```
Mitaka
Network Error
```
Not working services include urlscan.io, virustotal and hybridanalysis.
API Keys are valid.

Can i somehow provide logs for this?

**Comment by ninoseki** [comment]
@TrinityIsStillMyName please show the logs of failed HTTP requests.

**Comment by ninoseki** [comment]
Close this issue because there is no response for months.
