### ISSUE TITLE
Selected indicators in HTML preformatted text are not parsed as indicators

### ISSUE THREAD

**Issue by wesinator** [ninoseki/mitaka#392]
**to reproduce:**
HTML `<pre>Domain Name: example.com</pre>`

`example.com` is not parsed as a domain 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/5124946/76691855-dca75b80-6625-11ea-9946-982fa9e581b3.png">

Firefox 73.0.1 macOS

**Comment by ninoseki** [comment]
It doesn't happen in my env and there is no claim like this from users.
