### ISSUE TITLE
[Request] Email Leak Check

### ISSUE THREAD

**Issue by zero77** [ninoseki/mitaka#394]
Can you please add the below websites to check for leaked emails, thanks.

https://haveibeenpwned.com
https://monitor.firefox.com
https://haveibeensold.app

**Comment by ninoseki** [comment]
Could you tell me how can I integrate them like [this one](https://github.com/ninoseki/mitaka/issues/248), please?

**Comment by zero77** [comment]
I will have a more in-depth look but, it looks like the api has been updated and it now may or may not be possible.

**Comment by ninoseki** [comment]
Close this issue because there is no response for a long time.
