### ISSUE TITLE
[Request] reverse search images

### ISSUE THREAD

**Issue by zero77** [ninoseki/mitaka#395]
Can you please add the ability to reverse search images.
The below websites allow you to search images by adding the link to the image after the equals, see below, thanks.

https://www.google.com/searchbyimage?image_url= `link to image`
https://www.bing.com/images/searchbyimage?cbir=sbi&imgurl=
https://www.tineye.com/search?url=
https://karmadecay.com/search?q=
https://yandex.com/images/search?rpt=imageview&url=
https://graph.baidu.com/details?isfromtusoupc=1&tn=pc&carousel=0&image=&image=
https://st.so.com/stu?submittype=imgurl&src=image&srcsp=st_search&imgurl=
https://pic.sogou.com/ris?flag=1&drag=0&query=

**Comment by ninoseki** [comment]
Unfortunately the answer is no.
