### ISSUE TITLE
0.37.2 Firefox 76.0.1: Mitaka not showing in contextual menu

### ISSUE THREAD

**Issue by JayBrown** [ninoseki/mitaka#412]
Mitaka 0.37.2 is not showing in the contextual menu in Firefox 76.0.1 (macOS). Is there an additional setting to enable besides adding API keys etc.?

**Comment by ninoseki** [comment]
Please use the latest version.  v0.37.2 is too old version.

**Comment by JayBrown** [comment]
Oops, sorry, it was a typo… I'm using the latest 0.73.2.

**Comment by ninoseki** [comment]
It works in my env.

<img width="1073" alt="Screen Shot 2020-05-21 at 10 57 31 PM" src="https://user-images.githubusercontent.com/291028/82567552-7eb06a80-9bb8-11ea-99f0-5ca540c925a3.png">

**Comment by JayBrown** [comment]
Strange. Doesn't work here.

![img](https://i.imgur.com/1DWFXYj.jpg)

**Comment by ninoseki** [comment]
You should select a block of text to search.

**Comment by ninoseki** [comment]
Please read the README before asking a question.

**Comment by JayBrown** [comment]
Already tried that, but that can't be the reason: not working either.

![img](https://i.imgur.com/oeCpQd5.png)

**Comment by ninoseki** [comment]
Reinstalling might help. I not, I have no clue to fix the issue.
