### ISSUE TITLE
Add polyswarm hash lookup

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mitaka#427]
Like VT, polyswarm can be used for searching for file hashes, and they allow downloading samples from platform with a free account.
So, it may be useful for those who don't have VTI.

Eg. https://polyswarm.network/scan/results/file/{file_hash}

**Comment by ninoseki** [comment]
I will review your PR for this FR. (I do not want to implement this FR by myself because I cannot understand the value of PolysWarm)

**Comment by r0ny123** [comment]
Now, I agreed with you too and understood that. And yes, let's don't make mitaka noisy. anyway, closing this.
