### ISSUE TITLE
Chrome extension: add custom content-security-policy?

### ISSUE THREAD

**Issue by juju4** [ninoseki/mitaka#464]
https://crxcavator.io/report/bfjbejmeoibbdpfdbmbacmefcbannnbg/0.77.1 reports a current score of 394 but 377 is because of default csp.

from https://developer.chrome.com/extensions/contentSecurityPolicy
> Those that select manifest_version 2, have a default content security policy of:
> script-src 'self'; object-src 'self'

not sure exactly what can be tightened and if eventually some object can be set to none. maybe something like:
```
default-src 'none'; script-src 'self'; object-src 'self'; connect-src 'none'; img-src 'self'; style-src 'self'; upgrade-insecure-requests;
```

Thanks for the hard work!

**Comment by ninoseki** [comment]
> Packages that do not define a manifest_version have no default content security policy. Those that select manifest_version > 2, have a default content security policy of:
> 
> script-src 'self'; object-src 'self'

Then what is the risk? Could you explain it please?

**Comment by ninoseki** [comment]
@juju4 why did you create this issue if you don't know what is the risk?

**Comment by juju4** [comment]
Not answering immediately does not mean that I don't know or can't provide more feedback based on documentation.

My first thought was for attacks on other type of resources that script (javascript) or object (flash). for example websockets or fonts or whatever else will come in the future.
fonts have been shown useful for attacks on Windows. Even with Chrome sandboxing, they may be options there.
And I think that's also what crxcavator targets.

When digging crxcavator documentation
* https://crxcavator.io/docs#/changelog
> Extensions without a Content Security Policy will now account for the default CSP. Risk score 377
this does not account it seems of default CSP present in manifest version 2.
and
> The risk score of the default-src section of the Content Security Policy is now applied to sections that are not defined
> The following sections of the Content Security Policy are now scored: child-src, connect-src, font-src, form-action, frame-ancestors, frame-src, img-src, manifest-src, media-src, object-src, plugin-types, sandbox, script-src, strict-dynamic, style-src, upgrade-insecure-requests, worker-src
> A 'none' entry in the Content Security Policy now does not add any risk
> The 'unsafe-inline' and 'unsafe-eval' entries in the Content Security Policy will now count for 5 points each

also here
https://crxcavator.io/docs#/risk_breakdown?id=content-security-policy

This is also in initial crxcavator announcement
https://duo.com/blog/crxcavator
> Of the 95k extensions in the Web Store that support Content Security Policies at the time of our analysis, we found that 74,403 (78.3 percent) do not have a CSP defined and, beyond that, 94,059 extensions (99 percent) do not have default-src or connect-src in the CSP defined. These are the parts of the CSP that give developers the ability to restrict which external resources the extensions can access and where the extensions can send the data they collect.

From above, the implicit recommended CSP that I understand from their documentation is
```
default-src 'none'; script-src 'self'; object-src 'self';
```

**Comment by ninoseki** [comment]
@juju4 I am sorry if I may offend you.
Cloud you test the extension works with your sugeested CSP configuration, please?
To be honest, I feel your point is a little bit trivial and I am not willing to test it by myself.

**Comment by ninoseki** [comment]
@juju4 Do you have a willingness to work on this issue?
I will close this issue if you don't have it.

**Comment by juju4** [comment]
https://github.com/ninoseki/mitaka/pull/477
