### ISSUE TITLE
Renew README [help wanted]

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/mitaka#469]
English is not my native tongue. So I believe there are unnatural sentences/expressions in the README.
So please give your any suggestion to improve the README.  
Comments on this issue or PR is welcome.

**Comment by lumenCodes** [comment]
Okay
@ninoseki I haven't seen any unnatural expressions but the README needs a lot of work.
Example: what is OSINT?

So basically there are a lot of abbreviations that are not beginner friendly . Is there a way of providing their meaning?

**Comment by ninoseki** [comment]
@lumenCodes a PR is welcome but it should be meaningful one.
I'm not sure "what is OSINT?" thing is a meaningful for the README of this extension. Context matters.
You should make a pitch for that.

**Comment by lumenCodes** [comment]
What I am trying to say is that.. There are abbreviations in the README which a beginner like me do not understand... So writing the full meaning before the abbreviation might help out...  

**A screenshot**  
![image](https://user-images.githubusercontent.com/60603806/92497473-4ed1b500-f1f1-11ea-819f-dfd983c58751.png)

**Comment by rushowr** [comment]
OSINT = Open Source Intelligence

**Comment by rushowr** [comment]
@ninoseki, do you still wish for someone to assist further with this issue (English speaker, readme file, etc...)?

**Comment by ninoseki** [comment]
Yes I'd appreciate it if you could give me any meaningful feedback.

**Comment by rushowr** [comment]
Ninoseki, I will assist you to the best of my abilities. 
o7
