### ISSUE TITLE
unable to use it

### ISSUE THREAD

**Issue by ronak131313** [ninoseki/mitaka#473]
Upon right click, the option for mitaka doesn't appear. Please help.

**Comment by ninoseki** [comment]
Please share the detailed information about your environment and screenshots of how it does not work.

**Comment by ninoseki** [comment]
@ronak131313 I will close this issue if you don't share the information.

**Comment by ronak131313** [comment]
> @ronak131313 I will close this issue if you don't share the information.

Sorry buddy for the late response. It works now!!
