### ISSUE TITLE
Add VirusTotal

### ISSUE THREAD

**Issue by ZeroDot1** [ninoseki/mitaka#5]
Add the possibility to scan and search URLs and IPs via VirusTotal. 

_Thank you for your good work, the extension is very helpful._  :+1:

**Comment by ninoseki** [comment]
@ZeroDot1 thank you for your feedback.
Ok, I'll work on that.

**Comment by ZeroDot1** [comment]
Thank you very much :)

**Comment by ninoseki** [comment]
@ZeroDot1  I just added VT support in v0.6.0.  You can search URL/IP/Doman/Hash on VT via Mitaka now.
Could you please update the extension?

**Comment by ZeroDot1** [comment]
@ninoseki Thank you so much for adding it so fast it works very good. :+1:
