### ISSUE TITLE
right mouse click menu doesnt appear anymore [BUG]

### ISSUE THREAD

**Issue by feiercrack** [ninoseki/mitaka#558]
Windows 10 x64 Pro 2004
Mitaka 0.85.1
Brave Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-Bit)
also in ChromeVersion 89.0.4389.90 (Official Build) (64-Bit)
Mitaka Right-mouse click Menu doesnt appear anymore

also it is greyed-out in the extension menu on the upper right

what to do?
![1](https://user-images.githubusercontent.com/47046040/112728442-9f0f2b00-8f27-11eb-9c4b-f28dec933c66.png)
![2](https://user-images.githubusercontent.com/47046040/112728448-a2a2b200-8f27-11eb-8f9f-2e4306dea3be.png)

**Comment by ninoseki** [comment]
Excuse me, I know nothing about Brave.

The extension only supports Chrome and Firefox officially. I use Chrome on a daily basis and there is no problem.

**Comment by feiercrack** [comment]
> Excuse me, I know nothing about Brave.
> 
> The extension supports Chrome and Firefox officially. Brave is not supported.
> I use Chrome on a daily basis and there is no problem.

..as i wrote above, again:
also in Chrome Version 89.0.4389.90 (Official Build) (64-Bit)

**Comment by ninoseki** [comment]
Sorry, I overlooked that.

In my env (`Version 89.0.4389.90 (Official Build) (x86_64)`), there is no problem. 
I'm not sure but maybe something went corrupt in your env. Reinstalling the extension might work.

**Comment by feiercrack** [comment]
how can u close, if its even not solved?
