### ISSUE TITLE
I would like to publish this ext on the Chrome Store...

### ISSUE THREAD

**Issue by charlieporth1** [ninoseki/mitaka#571]
I would like to publish this ext on the Chrome Store; with your permission ofc. And free of charge. And only if you would like.

**Comment by ninoseki** [comment]
Why?

**Comment by ninoseki** [comment]
Excuse me, literally I cannot understand your suggestion.
This extension is already published in Chrome web store and Mozilla add-ons.
- https://chrome.google.com/webstore/detail/mitaka/bfjbejmeoibbdpfdbmbacmefcbannnbg
- https://addons.mozilla.org/en-US/firefox/addon/mitaka/
