### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by cocoonkid** [ninoseki/mitaka#586]
1. Make sure your requested feature makes sense for Mitaka:
I think it would help tremendously.

It would be super helpful if mitaka would mark IoC's and keywords/patterns automatically on websites.

Like simply adding a border around IP's and similar.l

The usability is a little hard when I have to remember or guess when/if the mitaka context menu would be available.

Thank you for your consideration.

similar to this:

![image](https://user-images.githubusercontent.com/43231640/124647202-f19ca380-de95-11eb-9b34-460ec3e88a94.png)

**Comment by ninoseki** [comment]
@cocoonkid Excuse me, what is it?

**Comment by cocoonkid** [comment]
Oh no , it got all deleted :)

**Comment by ninoseki** [comment]
My answer is same as [here](https://github.com/ninoseki/mitaka/issues/587#issuecomment-874475450)
