### ISSUE TITLE
[Feature Request]  Additional Visual indicator of IOC's

### ISSUE THREAD

**Issue by cocoonkid** [ninoseki/mitaka#587]
Additional Visual indicator of IOC's

It would be great if a simple colored border  could be shown on each and any possible Mitaka element.

It is a little difficult to remember or guess which elements the context menu will become active on.

Thank yo for your consideration.

**Comment by ninoseki** [comment]
> It would be great if a simple colored border could be shown on each and any possible Mitaka element.

It will be very annoying because Mitaka considers `a` links as URLs.
Also, I do not want to interfere DOMs on a web page. It might cause a problem I cannot expect.
