### ISSUE TITLE
[Feature Request] Consider prompt Y/N popup before opening 50+ tab

### ISSUE THREAD

**Issue by Dentrax** [ninoseki/mitaka#639]
![Screen Shot 2022-02-01 at 15 16 40](https://user-images.githubusercontent.com/16493751/151966997-5af74d36-323a-4b59-a1bb-559caf74d827.png)

It would be nice to add a popup called: `Are you want to open %d tabs?`.

**Comment by ninoseki** [comment]
Thanks for your suggestion. 
How about this? I know it's not well-looking but it's the easiest implementation (just using `window.confirm`) :wink:.

<img width="294" alt="Screen Shot 2022-02-02 at 11 35 32 AM" src="https://user-images.githubusercontent.com/291028/152084720-8bb54786-604f-495b-b051-4b1cc88e4455.png">

**Comment by Dentrax** [comment]
Seems nice. But getting rid of empty gaps would better.

**Comment by ninoseki** [comment]
As far as I know, there is no way to customize the UI of `window.confirm`.

**Comment by ninoseki** [comment]
#640 will be included in the next version `v0.90.1`.
