### ISSUE TITLE
[BUG] No right-Click Context-Menu

### ISSUE THREAD

**Issue by xRv9Fk0oQ6Da** [ninoseki/mitaka#667]
Hey, so I just installed and there's no right-click option inside the context-menu. 

Please fix this, for debug:
Windows 10, x64 bit - windows 10 home build;

> edit: after posting; it appeared. I'm willing to help debug.

**Comment by xRv9Fk0oQ6Da** [comment]
> > edit: after posting; it appeared.
> 
> So is the issue already fixed in your side? I guess it is a common issue in Google Chrome and I don't have a clue to fix it. https://github.com/ninoseki/mitaka#common-questions
Yes, it sorted itself out. I apologize about the report, I restarted and everything didn't want to kick in.
Great extension. Thank you.

**Comment by ninoseki** [comment]
No problem. I will close this issue.
