### ISSUE TITLE
Could you upload mitaka to Microsoft Edge Addons?

### ISSUE THREAD

**Issue by ANYLNK** [ninoseki/mitaka#678]
Someone who uses Microsoft Edge may can't access Chrome Webstore. (Example: in China)

Thanks for your consideration.

**Comment by ninoseki** [comment]
Thanks for the suggestion.
Unfortunately, I don't have a Windows machine. It means I cannot test the extension with MS Edge. I do not want to publish the extension without testing. So, my answer to your question is no.

But, this is an OSS project. So you can build the extension and load it by yourself.

```bash
$ npm install
$ npm run build
```
The command generates a zip file. You can unzip it and load it in MS Edge.

- [Sideload an extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading)
