### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IcyBear13** [ninoseki/mitaka#681]
### **Describe the bug**

I have installed the extension on brave and also firefox and both seem to do nothing. No menu shows up on the context menu.

### **Steps to reproduce**

- Right click acter secting text

### **System Information:**

- OS: [Windows10]
- Browser: [Brave]
- Mitaka version: [0.91.0]

### **Additional context**

I have tried deleting and reinstalling the addon already.

**Comment by ninoseki** [comment]
I just tested with the extension with Firefox 102.0.1 (64-bit). (Brave is out of scope of this extension)
There is nothing I can help you with when an issue is not reproducible.
Sorry but I think the last resort is using Chrome.

**Comment by EmeraldEngineer** [comment]
I tested with Brave (Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)) even though it is not explicitly supported by the extension, and I was able to successfully install and use Mitaka. I did notice that the extension occasionally exhibited some slightly erratic behavior while using Brave, but during my short test, the extension generally worked as expected.

**Comment by IcyBear13** [comment]
Not sure why but now it works just to let you know.
