### ISSUE TITLE
Apply Criminal IP as search engine to your further projects

### ISSUE THREAD

**Issue by resley-404** [ninoseki/mitaka#711]
Hello Ninoseki,

I came across your repersitory and found your Mitaka project very interesting!

I'd like to suggest you to apply Criminal IP to your daily work, maybe to your further projects using as a search engine!
It’s an OSINT-based search engine that allows users to search for malicious URLs, domains, and much more.

Take a look at https://www.criminalip.io/.
I'd like to hear your feedback.

Best.
Resley

**Comment by ninoseki** [comment]
https://github.com/edoardottt/awesome-hacker-search-engines/issues/25#issuecomment-1460486371
I will close this FR thanks to @edoardottt.
