### ISSUE TITLE
[bug] "Search domain/URL on all" opens all services even if they are disabled

### ISSUE THREAD

**Issue by testtest123333** [ninoseki/mitaka#712]
### **Describe the bug**

Clicking "Search <domain> on all" or "Search <URL> on all" opens a bunch of tabs of all searchers even if they are disabled in settings.

### **Steps to reproduce**

- Enable searchers in settings, disable unnecessary searchers. I have enabled the following:

> AbuseIPDB
> ANY.RUN
> archive.org
> archive.today
> Blockchain.com
> DomainTools
> GoogleSafeBrowsing
> IPinfo
> urlscan.io

- Select something and click on the context menu "Search * on all".

### **Expected behavior**

Only active searchers included and visible in the context menu are opened.

### **Actual behavior**

A whole bunch of tabs is opened, ignoring that these searchers are disabled.
The prompt "Are you sure you want to open XX tabs?" is not shown.

### **Screenshots**

![1](https://user-images.githubusercontent.com/99139463/226135146-3f9d8103-c7c1-42be-9c40-05d91256980e.png)
![2](https://user-images.githubusercontent.com/99139463/226135167-d6755ccd-d29b-4561-b639-ea86618fb72c.png)

### **System Information:**

- OS: Windows 10
- Also tested on Ubuntu 22.10
- Browser: Chromium 111.0.5563.65
- Also tested on ungoogled-chromium 111.0.5563.71
- Mitaka version: 1.0.0 (Latest)

### **Additional context**

Appeared only in 1.0.0, previous version installed was 0.93.0 and worked as expected.

**Comment by ninoseki** [comment]
Thanks for the heads up.
The next version (v1.1.0) will include the fix for the issue.
