### ISSUE TITLE
[Feature request] Add more options to enable/disable searchers in settings

### ISSUE THREAD

**Issue by testtest123333** [ninoseki/mitaka#713]
- Add an "Enable/Disable all" toggle.

Could be useful when reloading/reinstalling the extension, and if only a few services need to be enabled.

![3](https://user-images.githubusercontent.com/99139463/226139707-5c5ac310-2db7-4dd5-9adf-2a1963fb9474.png)

- Add an option to disable scanning engines.

Could be useful in specific cases e.g. when it's known that the engine is unable to scan a site (geoblocked sites, sites requiring referer header etc.), or when checking links containing PII that are not to be submitted anywhere, especially by accident.
If both search and scan engine (urlscan, HybridAnalysis, VirusTotal), handle them separately. Could look like this:

![4](https://user-images.githubusercontent.com/99139463/226139719-a521a66a-8cf5-4999-a0ef-05f6498fdfd3.png)

Or:
/
![5](https://user-images.githubusercontent.com/99139463/226139741-2d120738-1415-4759-b23e-c25e6dee7828.png)

- Add an option to remove the "Search domain/URL on all" context menu.

Could be useful for people (like me) who often misclick or use keyboard navigation too quickly and select a wrong entry.

![6](https://user-images.githubusercontent.com/99139463/226139912-a991509e-7e6e-4d7e-b7f3-96b70f27dd41.png)

**Comment by ninoseki** [comment]
You partially expose your VT API key (61 length). It's easy to guess/brute-force the remaining. So please delete the image or masking the section.
