### ISSUE TITLE
[1.0.0] lost content-security-policy

### ISSUE THREAD

**Issue by juju4** [ninoseki/mitaka#718]
### **Describe the bug**

With MV3 change (https://github.com/ninoseki/mitaka/blame/d03b9a65e00eacc5b96af05a30e5b29240feeedf/package.json), part of manifest including specific content-security-policy from https://github.com/ninoseki/mitaka/pull/477/files has been lost.
Risk score on https://crxcavator.io/report/bfjbejmeoibbdpfdbmbacmefcbannnbg/ up to 395 in 1.0.0

Is this intended?
If not, can it be restored?

Thanks

### **Steps to reproduce**

- Check https://crxcavator.io/report/bfjbejmeoibbdpfdbmbacmefcbannnbg/
- Or check resulting manifest content-security-policy

### **Expected behavior**

- Lower risk/score
- No known feature impact

### **Actual behavior**

- Higher risk/score
- No known feature impact

### **Screenshots**

N/A

### **System Information:**

- OS: N/A
- Browser: N/A
- Mitaka version: 1.0.0

### **Additional context**

N/A

**Comment by ninoseki** [comment]
To be honest, I forgot about CSP while working on the MV2 to MV3 migration.
But, in MV3 era, I'm not sure how much setting CSP is meaningful. Why the default policy is not enough?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by juju4** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#default_content_security_policy says
```
"script-src 'self'; upgrade-insecure-requests;"
```
Top page example https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy
```
"content_security_policy": {
  "extension_pages": "default-src 'self'"
}
```
The first one only restrict javascript/webassembly part.
The second apply to all content, existing or futures ones, typically img, media, css, also fonts or frames as per https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Considering this was already working before, cost is low and it ensures all content coverage explicitly.
If new features were introduced in 1.0.0, it may need an update (new website XHR call?)

**Comment by ninoseki** [comment]
In MV3, `script-src` directive and `object-src` directive (and also `default-src` directive) can be customizable. Other directives don't.
The default policy (`"script-src 'self'; upgrade-insecure-requests"`) looks enough.

**Comment by juju4** [comment]
Both mozilla and chrome example pages are using default-src
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy
https://developer.chrome.com/docs/extensions/migrating/improve-security/#update-csp
Some attacks can be done through css, image, frame or other than javascript.
If inside MV3 extension, there is no usage for any other content other than javascript, may be fine but how to demonstrate it?

I'm fine to report no issue including to crxcavator to update their scoring but some documentation support would be necessary I believe.

**Comment by ninoseki** [comment]
Why should I take care about CRXcavator score? 
Does your company/organization have a policy based on that? For example, a high score extension is not allowed to install.

**Comment by juju4** [comment]
More or less, yes.
Crxcavator is AFAIK the only public evaluation tool for browser extensions.
Individual extension review, pentest or whatever assessment are not scalable and more driven by higher risks identified.

**Comment by ninoseki** [comment]
Could you rescan the extension in the service, please?

**Comment by juju4** [comment]
Thanks @ninoseki !

The only rescan I see is from web UI but it does not seem to happen as still on 1.1.0 as latest version and not 1.1.1
https://crxcavator.io/report/bfjbejmeoibbdpfdbmbacmefcbannnbg?platform=Chrome&new_scan=true
with "LAST UPDATED 2023-03-25"
1.1.1 correctly listed on chrome store https://chrome.google.com/webstore/detail/mitaka/bfjbejmeoibbdpfdbmbacmefcbannnbg

From https://crxcavator.io/docs.html#/README
> CRXcavator automatically scans the entire Chrome, Firefox, and Edge Web Stores every 3 hours and produces a quantified risk score for each browser extension based on several factors.

Likely backend issue. I will reach out to them. Good to gather more information anyway.

A bit more details on their CSP risk breakdown on this page:
https://crxcavator.io/docs.html#/risk_breakdown?id=content-security-policy
notably
> The default-src risk will be applied to all sections of the CSP that are not defined
> Any extension (not application) that does not define a CSP will have a risk score of 377 (15 * 25 for missing sections and 1 point each for script-src and object-src which are default 'self')

**Comment by ninoseki** [comment]
There is no progress. I think there is an issue on CRXcavator side. 
So let me close this issue.

**Comment by juju4** [comment]
yeah. sorry about that. Thanks a lot for the changes!
I reached to them. will see if feedback.
