### ISSUE TITLE
[BUG] Search all not working anymore for hashes

### ISSUE THREAD

**Issue by ahmedxuae91** [ninoseki/mitaka#719]
Search all used to work fine with Hashes. However, recently we started facing an issue indicating some sources accepts specific types only (e.g. MD5 only or SHA256 only )

![image](https://user-images.githubusercontent.com/21212837/228250125-dd2e2f25-43ce-44c8-bc16-eeeaab084e22.png)

Version used: 1.1.0

**Comment by ninoseki** [comment]
Thanks for reporting. I fixed the issue and the next version (v1.1.1) will include the fix.
