### ISSUE TITLE
[Feature Request] Some ideas for additional sources and features. 

### ISSUE THREAD

**Issue by d3f3nder** [ninoseki/mitaka#731]
Hi first i would like to say thank you ;) Mitaka is a great tool!

There are maybe some nice features / sources which could be beneficial for some more  investigation options. 

- LOLBAS, Living of the land binaries/extensions/drivers/dll info
sites like: 
filesec.io
loldrivers.io
lolbas-project.github.io
hijacklibs.net

IOCs would be '.exe, .sys,  file extentions, dll's etc. ' 

- A subnet / cidr lookup
site like: 
https://mxtoolbox.com/SubnetCalculator.aspx
IOC: ip

- URL decoder
sites like:
urldecoder.io
IOC: url

- URL unshorten
sites like:
checkshorturl.com
IOC: URL

- URL unfurl
sites like: 
https://difr.blog/unfurl/
IOC: URL

- Site built info
sites like:
builtwith.com
IOC: URL

- Breach lookup
sites like: 
haveibeenpwned.com
IOC: email

- Internet archive snapshot lookups
sites like:
archive.org/web
IOC: URL

- URL redirect inspection
sites like:
redirectdetective.com
IOC: URL

- User agent lookup
sites like:
explore.whatismybrowser.com/useragents/parse/
IOC: user agent string

and i've noticed the Zscaler Zulu url inspection service is not on the list:
zulu.zscaler.com
IOC: URL

Just some ideas! keep up the great work, i am really enjoying this tool. 

regards

**Comment by ninoseki** [comment]
> https://mxtoolbox.com/SubnetCalculator.aspx
Impossible.

> urldecoder.io
Impossile.

> checkshorturl.com

Impossible.

> https://difr.blog/unfurl/
Dead link.

> builtwith.com
Possible

> haveibeenpwned.com
Impossible.

> archive.org
Already supported.

> redirectdetective.com
Impossible.

> explore.whatismybrowser.com/useragents/parse/
Impossible.

---

I'd consider BuiltWith support if you create a feature request following the template.
