### ISSUE TITLE
[Feature Request] Include new source labs.inquest.net

### ISSUE THREAD

**Issue by ahmedxuae91** [ninoseki/mitaka#744]
Hi,

I believe adding this source would be beneficial https://labs.inquest.net/ as it contains a good db for multiple IoC types.

**Comment by ninoseki** [comment]
Thanks for the suggestion but how can I integrate it?

**Comment by ahmedxuae91** [comment]
It is similar on how other sources are used, just need to append the IoC after https://labs.inquest.net/iocdb/search/ .. for example: https://labs.inquest.net/iocdb/search/57ebd5a707eb69dd719d461e1fbd14f98a42c6c3dcb8505e4669c55762810e70

**Comment by ninoseki** [comment]
Hmm, it looks like the link shows irrelevant results which is not suitable for this extension.

**Comment by ninoseki** [comment]
Could you re-check it and fill the issue template (feature request template), please?
Then I will check this request again.

**Comment by ninoseki** [comment]
I will close this issue because there's no response for a long time.
