### ISSUE TITLE
Windows 11 - Firefox 119.0 - No Context Menu Appears[BUG]

### ISSUE THREAD

**Issue by kirtcathey** [ninoseki/mitaka#766]
As the title states... installed Mitaka extension into stated configuration. When I highlight anything - domain name, ip address, name - no context menu appears. Have searched high and low related to FF and of course the Win 11 context menu stuff...
### **Describe the bug**

Cannot use the extension because it does not appear in the context menu when I highlight things to OSINT search.

### **Steps to reproduce**

In stated configuration, highlight things to search and right-click. There will be no context menu.

### **Expected behavior**

A context menu should appear.

### **Actual behavior**

No context menu appears.

### **Screenshots**

Add screenshots to help explain your problem.

### **System Information:**

- OS: Windows 11
- Browser: Firefox 119.0
- Mitaka version: 1.3.3

**Comment by ninoseki** [comment]
I guess you don't set this configuration.
https://github.com/ninoseki/mitaka#firefox

**Comment by ninoseki** [comment]
I will close this issue if there is no response.
