### ISSUE TITLE
[Feature Request] criminalip.io

### ISSUE THREAD

**Issue by hbednar** [ninoseki/mitaka#769]
Can you add criminalip.io it's similar to Shodan

- Base URL https://www.criminalip.io
- IoC types IP
- URLs for each IoC:
  - IP(1.1.1.1): https://www.criminalip.io/asset/report/1.1.1.1

Other options:
![2023-11](https://github.com/ninoseki/mitaka/assets/71215137/91071139-08ea-4f4d-9958-440a43276197)

**Comment by ninoseki** [comment]
I think CriminalIP is a scammy service because Shodan creator claims [they actually stole Shodan data without permission](https://www.reddit.com/r/netsecstudents/comments/uecss8/shodan_vs_criminal_ip/) so please let me close this proposal.
