### ISSUE TITLE
[Feature Request] Favicon Support

### ISSUE THREAD

**Issue by hbednar** [ninoseki/mitaka#770]
Can you please add website favicon support to the context menu as it makes it easier to find the website you are looking for.

Example from [Sputnik OSINT Extension](https://github.com/mitchmoser/sputnik):

![2023-11](https://github.com/ninoseki/mitaka/assets/71215137/72dd101f-812b-4253-b83e-568a880e3ee2)

**Comment by ninoseki** [comment]
Mitaka is built for [Chrome Extension Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/).
Manifest V3 does not support showing an icon in the context menu.
Sputnik's Firefox extension shows icons because it's built upon Manifest V2.
