### ISSUE TITLE
[BUG] Mitaka (wasn't) showing up in context menu till I installed and reinstalled it 5 separate times. Now works so yay but was inconsistent previously. Just concerned is all. 

### ISSUE THREAD

**Issue by Joshua079** [ninoseki/mitaka#784]
### **Describe the bug**

I was typing this bug report all out with Mitaka uninstalled (after installing and uninstalling then giving up 4 separate times), then all of a sudden it worked so I thought I'd make this anyways bc I have no idea why it's suddenly working and I'm concerned this may be a broader issue. 

### **Steps to reproduce**

I just installed from the chrome webstore like normal and it would not work for a long while, till it finally did indeed work after the 5th install. I did not have debugging enabled for any of the times so I have no personal logs to attach or show. 

### **Expected behavior**

Mitaka to appear in the context menu within a reasonable time without uninstalling and reinstalling... 

### **Actual behavior**

Mitaka did not appear for a long while and after many reinstalls till it finally did out of no where RIGHT away in the 5th install (immediately for some reason. Took no time at all and just started working)

### **Screenshots**

N/A

### **System Information:**

- OS: Windows 11
- Browser: Latest version of Brave
- Mitaka version: Latest at the moment from webstore (version number not technically given sadly)

### **Additional context**

Just a ps, yes I 100% did accept the permissions every single time I reinstalled.

**Comment by ninoseki** [comment]
Thanks for reporting and sorry that I do tests with macOS+ Chrome & Firefox. (I don't have a Windows machine)
If you want to use this extension, could you consider using Chrome, please? There is no such issue in there as far as I know.

**Comment by ninoseki** [comment]
I will close this issue if there is no response within a week.
