### ISSUE TITLE
Possible Firefox Issue (latest FF Win11)

### ISSUE THREAD

**Issue by scafroglia93** [ninoseki/mitaka#795]
Hi, I installed and enabled the extension with additional permissions but I can't get it to start. As per the screenshot there is no setting to insert the APIs of the various services

![Screenshot 2024-02-24 163342](https://github.com/ninoseki/mitaka/assets/8227101/b71136cf-6f02-4d2d-80b2-f9670c231604)

Maybe i miss something ?

**Comment by ninoseki** [comment]
I tested the extension (v2.0.0) with Firefox 123.0 (64-bit) and there is no issue like you claimed.

<img width="1085" alt="Screenshot 2024-02-25 at 14 19 25" src="https://github.com/ninoseki/mitaka/assets/291028/67d2c3a5-726a-4b48-842e-ae30037ccd3b">
<img width="960" alt="Screenshot 2024-02-25 at 14 19 39" src="https://github.com/ninoseki/mitaka/assets/291028/696f6020-2772-4fb5-91f1-e055f2a099ba">

Also you don't follow the issue template so I will close this issue.

**Comment by ninoseki** [comment]
I can reproduce the issue by myself and I fixed the issue in the latest version. 
https://addons.mozilla.org/en-US/firefox/addon/mitaka/
Please try it.

**Comment by scafroglia93** [comment]
Fixed, TOP
