### ISSUE TITLE
[Feature Request] Hudson Rock Cybercrime Intelligence

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [ninoseki/mitaka#804]
Consider adding Hudson Rock's complimentary data to your enrichment stack to check if an email address or domain was compromised in a global Infostealer attack.

- Base URL: https://www.hudsonrock.com/
- IoC types: email, domain
- Email API sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com
- Domain API sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-domain?domain=tesla.com

Thank you.

**Comment by ninoseki** [comment]
So does the application only supports JSON endpoints?

**Comment by hudsonrock-partnerships** [comment]
Yes. We have complete API documentation including a free public API key for additional information.
https://cavalier.hudsonrock.com/docs

**Comment by ninoseki** [comment]
I feel it's all about marketing. I will take a look at it if someone creates a PR for this request. But I don't do it by myself.
