### ISSUE TITLE
Firefox Addons-support

### ISSUE THREAD

**Issue by aancw** [ninoseki/mitaka#81]
Hi there, 

Do you have a plan to support & porting Firefox addons compatible too? I'm interested with this tool :+1: 

Cheers,

**Comment by ninoseki** [comment]
I agree that Firefox support would be good.
Unfortunately, current implementation of this extension is highly tied with Chrome extension API.
I'll check Firefox extension API to check whether can I port this extension to Firefox.

**Comment by aancw** [comment]
Ah, glad to hear that. I'm also still looking for IOCs with python support for my project.

**Comment by aancw** [comment]
If you don't mind, you can look at this resource:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by ZeroDot1** [comment]
At the moment I'm working with Firefox because it's a bit faster and safer, a version of Mitaka for Firefox I would appreciate very much.

**Comment by ninoseki** [comment]
@aancw @ZeroDot1 
I just released a FireFox version of this extension.
https://addons.mozilla.org/en-US/firefox/addon/mitaka/
Note that I don't do full-spec testing on FF. Please try it and let me know if you have any issues.
