### ISSUE TITLE
[BUG] Mitaka `v2.1.2` Fails to Load After IoC Selection

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mitaka#821]
### **Describe the bug**

The latest version of Mitaka fails to load after selecting an IoC, such as an IP address.

### **Expected behavior**

After selecting an IoC, Mitaka should appear in the menu upon left-click.

### **Actual behavior**

Mitaka does not load or appear in the menu.

### **Screenshots**

![Screenshot (142)](https://github.com/user-attachments/assets/4f2fc454-e859-462d-891d-c812b8aac405)

### **System Information:**

- OS: Windows10
- Browser: Edge127.0.2651.74 
- Mitaka version: Latest

### **Additional context**

The issue does not occur in Mitaka version 2.1.1, which loads correctly.

**Comment by ninoseki** [comment]
Fixed in the latest version.

**Comment by r0ny123** [comment]
Thanks for the quick fix. Works fine now.
