### ISSUE TITLE
Scanning hyperlinks without selecting them

### ISSUE THREAD

**Issue by Kezxo** [ninoseki/mitaka#96]
Would be nice to have the ability to scan links without selecting it or being able to scan any hyperlink.

**Comment by ninoseki** [comment]
@Kezxo I'm not sure the implementation image. Could you provide more details?

**Comment by Kezxo** [comment]
@ninoseki I mean you should be able to right click any hyperlink and scan the url using the right click menu

Last I checked you can scan links like this:

https://github.com/

But this can't be scanned:

[github](https://github.com/)

Maybe this is outside of the goals for this extension, I just thought it would be useful for me.

**Comment by ninoseki** [comment]
Nope it can be scanned.

<img width="782" alt="Screen Shot 2020-05-31 at 8 32 24 PM" src="https://user-images.githubusercontent.com/291028/83351328-ebc4bc80-a37d-11ea-87b9-c57f38b8b387.png">

**Comment by Kezxo** [comment]
Huh, Ok. I didn't think it worked like that. But notice that you had to highlight it, that was the original idea with my suggestion. What if you only had to right click it?

Here is an example why the highlighting thing can be problematic: on the [github frontpage](https://github.com/) that i visited while logged out: 

![image](https://user-images.githubusercontent.com/4523551/83352665-793be880-a34d-11ea-9cc6-557b57060972.png)

That link, that says ``start a free trial`` can't be highlighted so it can't be scanned. I can still copy the link though.

That was my original issue, right clicking links should let you scan them.
