### ISSUE TITLE
Add loading to the end of the link when you scan with urlscan to avoid the 404 error.

### ISSUE THREAD

**Issue by Kezxo** [ninoseki/mitaka#97]
Example:
Current link you get when you scan a url with urlscan:
https://urlscan.io/result/54db15c2-5246-4f5c-9907-7576ce5b7547/ This will produce a 404 since the scan isn't done, you have to refresh manually.

Possible solution:
Add ``loading`` to the end like this:
https://urlscan.io/result/54db15c2-5246-4f5c-9907-7576ce5b7547/loading
This will produce a page that shows the progress of the scan and refreshes automatically when it's done.

**Comment by ninoseki** [comment]
@Kezxo thanks, I implemented it.

**Comment by Kezxo** [comment]
Great! Thanks for the extension.
